version: '3'

services:
  fastapi:
    build: .
    ports: [ "8000:8000" ]
    command: [ "poetry", "run", "uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000" ]
    depends_on: [ redis ]

  worker:
    build: .
    command: [ "poetry", "run", "celery", "-A", "worker.app", "worker", "--beat", "--loglevel=info" ]
    depends_on: [ redis ]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  flower:
    build: .
    command: [ "poetry", "run", "celery", "-A", "worker.app", "flower" ]
    depends_on: [ redis ]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports: [ "5555:5555" ]

  redis:
    image: "redis:latest"
    ports: [ "6379:6379" ]
