"""add column

Revision ID: 3c487e369191
Revises: 3b028b205a91
Create Date: 2024-04-15 15:29:49.140187

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c487e369191"
down_revision: str | None = "3b028b205a91"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("traders", sa.Column("ws_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("traders", "ws_active")
    # ### end Alembic commands ###
